In [21]:
l = [1, 2, 3, 4, 5]

In [24]:
l2 = [w**2 / sum([i**2 for i in l]) for w in l]

In [25]:
print(l2)

[0.01818181818181818, 0.07272727272727272, 0.16363636363636364, 0.2909090909090909, 0.45454545454545453]


In [26]:
print(sum(l2))

1.0


In [28]:
import numpy as np

In [70]:
actions = [np.random.uniform(low=-0.1, high=0.1, size=2) for _ in range(5)]

In [78]:
print(actions)

[array([-0.01834046,  0.09066665]), array([ 0.04309803, -0.07922735]), array([0.06735341, 0.07064989]), array([-0.03908238,  0.02543282]), array([-0.00860897, -0.05086384])]


In [79]:
std = np.std(actions, axis=0)

In [80]:
mean = np.mean(actions)

In [85]:
new_actions = [np.random.normal(mean, std) for _ in range(10)]

In [86]:
new_actions

[array([0.02341705, 0.06926702]),
 array([-0.04705751, -0.00648208]),
 array([-0.03334277,  0.00111931]),
 array([0.01618541, 0.08317296]),
 array([0.00585712, 0.03945945]),
 array([0.00408323, 0.07974518]),
 array([ 0.02039027, -0.11191175]),
 array([-0.03681902,  0.03424252]),
 array([-0.004885  , -0.03346658]),
 array([ 0.04051398, -0.08861917])]

In [108]:
test = [10, 4, 23 , 2, 5]
ind = np.argsort(test, axis=0)[-3:][::-1]

In [110]:
[new_actions[i] for i in ind]

[array([-0.03334277,  0.00111931]),
 array([0.02341705, 0.06926702]),
 array([0.00585712, 0.03945945])]

In [131]:
step_size = 1
mean = 0
sd = 0
actions = [np.random.uniform(low=-step_size, high=step_size, size=2).astype(np.float32) for _ in range(5)]
for i in range(100):
#     print(actions)
    sample_outputs = [np.linalg.norm(action) for action in actions]
#     print(sample_outputs)
    top_ind = np.argsort(sample_outputs, axis=0)[-2:][::-1]
#     print(top_ind)
    top_samples = [actions[ind] for ind in top_ind]
#     print(top_samples)
    mean = np.mean(top_samples, axis=0)
    print(mean)
    sd = np.std(top_samples, axis=0)
    print(sd)
    actions = [np.random.normal(mean, sd) for _ in range(5)]
#     print(actions)
#     print('')

[ 0.01379338 -0.1592029 ]
[0.7283771  0.26315916]
[ 0.22601568 -0.25114656]
[0.80331142 0.18384332]
[ 1.13880772 -0.31120858]
[0.11422713 0.07427012]
[ 1.30395315 -0.16684041]
[0.03041279 0.00985137]
[ 1.33311928 -0.16484239]
[0.00397981 0.0009319 ]
[ 1.33894808 -0.16514519]
[3.16516232e-03 1.80765795e-05]
[ 1.34317553 -0.16515335]
[5.98921620e-04 8.45380238e-06]
[ 1.34394083 -0.16515996]
[9.46331356e-05 6.78670917e-06]
[ 1.34406906 -0.16515492]
[4.97551400e-05 3.23391827e-06]
[ 1.34410158 -0.16515648]
[9.26946120e-06 4.94741768e-06]
[ 1.34410793 -0.1651483 ]
[2.99151911e-06 3.89069376e-06]
[ 1.34410951 -0.16514475]
[3.99699512e-06 4.45877111e-06]
[ 1.34411454 -0.16514493]
[2.64000929e-06 1.99121800e-06]
[ 1.344118   -0.16514309]
[5.97603367e-07 1.31109842e-06]
[ 1.34411834 -0.16514432]
[1.01007513e-07 7.35467817e-07]
[ 1.34411839 -0.16514475]
[3.73745179e-08 1.35287891e-07]
[ 1.34411843 -0.16514482]
[1.63407488e-08 6.70425919e-08]
[ 1.34411844 -0.16514487]
[8.53120441e-09 1.19183899e-

In [132]:
import collections

In [133]:
d = collections.deque(maxlen=5)

In [134]:
d

deque([])

In [137]:
for i in range(10):
    d.append(i)

In [138]:
d

deque([5, 6, 7, 8, 9])

In [142]:
a = 409

In [143]:
b = 1

In [144]:
print(a%b)

0
